package exceptions;

/*
An exception can be generated by one
method and caught by another
 */
class ExcTest {
    //Generate an exception
    static void getException() {
        int nums[] = new int[4];
        System.out.println("Before exception is generated.");

        //generate an index-out-of-bounds exception
        nums[7] = 10; //exception generated here
        System.out.println("Thia will not be displayed");
    }
}

class ExcDemo2 {
    public static void main(String[] args) {
        try {
            ExcTest.getException();
        } catch (ArrayIndexOutOfBoundsException exc) {
            //catch the exception
            System.out.println("Index out-of-bounds!");
        }
        System.out.println("After catch statement.");
    }
}
